# Site settings
title: CV | HAIRGELY
description: hairgely's CV
favicon: /assets/img/share-972389_960_720.png
baseurl: https://hairgely.github.io/resume
url: https://hairgely.github.io/resume
rss_url: /pages/atom.xml
google_analytics: #UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: hairgely
  title: Developer
  address: Seoul
  email: hairgely@gmail.com
  link: https://hairgely.github.io
  weibo:
  github: hairgely
  facebook: hairgely
  linkedin: hairgely
  twitter: hairgely
  gavatar: /resumecard/assets/img/share-972389_960_720.png
  stackoverflow:
#  stackoverflow: 4582127
#  workHistory:
#    - work1:
#      company: Finzsoft Solutions Ltd
#      location: Auckland, New Zealand
#      title: Java Developer
#      started: 2014
#      duration: (2014 - Present)
#      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
#    - work2:
#      company: Agfa HealthCare
#      location: Shanghai, China
#      title: Java Developer
#      started: 2012
#      duration: (2012 - 2014)
#      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
#    - work3:
#      company: Citigroup Services and Technology (China) Limited
#      location: Shanghai, China
#      title: Java Developer
#      started: 2009
#      duration: (2009 - 2012)
#      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  projectHistory:
    - project1:
      name: Appboy 기술영업 및 고객 지원 
      location: Seoul, Korea
      company: 미디어로그
      started: 2016
      duration: (2016.02 - 2016.12)
      description: 모바일 광고 자동화 솔루션 
    - project2:
      name: O2O 출장세차 
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.09 - 2015.11)
      description: Spring, MyBatis, MariaDB, Java, JSP, Jquery
    - project3:
      name: 추천시스템(프로토타입)
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.09 - 2015.11)
      description: Apache Spark, Fluentd, Embulk, Logstash, Elasticsearch, Scala, AWS 
    - project4:
      name: 오픈가든
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.06 - 2015.10)
      description: Spring, MyBatis, MariaDB, Java, JSP, Jquery  
    - project5:
      name: 만화1번지 - 검색서버
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.04 - 2016.12)
      description: Apache Solr, Fruentd, Mysql 
    - project6:
      name: 만화1번지 - 정산, 통계 서버
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.04 - 2016.12)
      description: Spring, MyBatis, MariaDB, Java, JSP, Jquery, Batch
    - project7:
      name: 만화1번지 - Front, CMS 유지보수
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.04 - 2016.12)
      description: Spring, MyBatis, MariaDB, Java, JSP, Jquery, 
    - project8:
      name: 만화1번지 - Android
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.04 - 2016.12)
      description: Android
    - project9:
      name: 기타 프로젝트(프로토타입)
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.04 - 2016.12)
      description: 이미지 얼굴인식 (MS FaceApi), 실시간 로그 수집(ELK, AWS), 모니터링 시스템 (Logstash), 모바일 쿠폰 서비스, T-AR (Android)
    - project3:
      name: 추천시스템(프로토타입)
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.09 - 2015.11)
      description: Apache Spark, Fluentd, Embulk, Logstash, Elasticsearch, Scala, AWS 
    - project3:
      name: 추천시스템(프로토타입)
      location: Seoul, Korea
      company: 미디어로그
      started: 2015
      duration: (2015.09 - 2015.11)
      description: Apache Spark, Fluentd, Embulk, Logstash, Elasticsearch, Scala, AWS 
#  languages:
#    - language1:
#      name: Chinese
#      proficiency: Native
#    - language2:
#      name: English
#      proficiency: Professional
#    - language3:
#      name: Japanese
#      proficiency: Limit
  companyHistory:
    - company1:
      name: 미디어로그 (데이콤멀티미디어인터넷)
      proficiency: 2015.04 - 2016.12
    - company2:
      name: 포위드닷컴
      proficiency: 2013.05 - 2014.10
    - company3:
      name: PNPSOFT (NSOFT 모바일 자회사)
      proficiency: 2011.02 - 2011.11
    - company4:
      name: NSOFT (한국 지사)
      proficiency: 2010.02 - 2011.01
    - company5:
      name: NSOFT (일본 본사)
      proficiency: 2007.09 - 2010.01
  certificates:
    - certificate1:
      name: 정보처리기사
      proficiency: 기사
    - certificate2:
      name: 컴퓨터활용능력 
      proficiency: 2급
    - certificate3:
      name: JLPT
      proficiency: 2급
  educationHistory:
    - education1:
      name: AWS 에센셜 (세종대학교)
      proficiency:  2016
    - education2:
      name: 클라우드 컴퓨팅을 위한 하둡 (삼성SDS 멀티캠퍼스)
      proficiency:  2014
    - education3:
      name: 빅데이터 분석을 위한 R 프로그래밍 (SKT T아카데미)
      proficiency:  2014
  academicAbility:
    - academy1:
      name: 동국대학교  컴퓨터공학 대학원
      proficiency: 수료
    - academy2:
      name: 관동대학교  경제학과
      proficiency: 졸업
  programmingSkills:
    - skill1:
      name: HTML2
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%