# Site settings
title: CV | HAIRGELY
description: hairgely's CV
favicon: /assets/img/share-972389_960_720.png
baseurl: https://hairgely.github.io/resume
url: https://hairgely.github.io/resume
rss_url: /pages/atom.xml
google_analytics: #UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: hairgely
  title: Developer
  address: Seoul
  email: hairgely@gmail.com
  link: https://hairgely.github.io
  weibo:
  github: hairgely
  facebook: hairgely
  linkedin: hairgely
  twitter: hairgely
  gavatar: /resumecard/assets/img/share-972389_960_720.png
  stackoverflow:
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Finzsoft Solutions Ltd
      location: Auckland, New Zealand
      title: Java Developer
      started: 2014
      duration: (2014 - Present)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work2:
      company: Agfa HealthCare
      location: Shanghai, China
      title: Java Developer
      started: 2012
      duration: (2012 - 2014)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
    - work3:
      company: Citigroup Services and Technology (China) Limited
      location: Shanghai, China
      title: Java Developer
      started: 2009
      duration: (2009 - 2012)
      description: I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description. I am not a description. I am not description.I am not description.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Japanese
      proficiency: Limit
  certificates:
    - certificate1:
      name: 정보처리기사
      proficiency: 기사
    - certificate2:
      name: 컴퓨터활용능력 
      proficiency: 2급
    - certificate3:
      name: JLPT
      proficiency: 2급
  educationHistory:
    - education1:
      name: AWS 에센셜 (세종대학교)
      proficiency:  2016
    - education2:
      name: 클라우드 컴퓨팅을 위한 하둡 (삼성SDS 멀티캠퍼스)
      proficiency:  2014
    - education3:
      name: 빅데이터 분석을 위한 R 프로그래밍 (SKT T아카데미)
      proficiency:  2014
  academicAbility:
    - academy1:
      name: 동국대학교 대학원 컴퓨터 공학과
      proficiency: 수료
    - academy2:
      name: 관동대학교  경제학과
      proficiency: 졸업
  programmingSkills:
    - skill1:
      name: HTML2
      percentage: 100%
    - skill2:
      name: Bootstrap
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 70%
    - skill4:
      name: AngularJS
      percentage: 70%
    - skill5:
      name: Java/Java EE
      percentage: 90%